language: bash

# Cache Ubuntu packages:
cache: apt

# Make global environment:
env:
    global:
        - PATH=".:$PATH"

before_install:
    - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ precise main universe restricted multiverse"
    - sudo apt-get update 
    # failed packages: epubcheck 
    - sudo apt-get install -y automake autoconf autotools-dev libtool shtool checkbot dia ghostscript imagemagick inkscape poppler-utils transfig
    - sudo apt-get install -y python-libxml2 python-lxml libimage-exiftool-perl optipng
    - sudo apt-get install -y libxml2-utils libxslt1.1 xsltproc libxml2 xmlstarlet sgml-base sgml-data
    - sudo apt-get install -y jing docbook docbook-xml docbook5-xml docbook-xsl docbook-xsl-ns docbook-xsl-saxon libxml-commons-external-java libxmlgraphics-commons-java fop remake w3m xfig
    #- sudo apt-cache show docbook-xml
    #- sudo apt-cache show docbook-xsl
    - git clone https://github.com/openSUSE/suse-xsl.git suse

install:
    - ./.travis-debug
    - ./configure && make install 

script:
    # - make test
    - echo "Done"
