language: bash

# Cache Ubuntu packages:
cache: apt

# Make global environment:
env:
    global:
        - PATH=".:$PATH"

before_install:
    - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ precise main universe restricted multiverse"
    - sudo apt-get update 
    # failed packages: epubcheck xmlformat-perl
    #
    # DO NOT USE TABs in the following section!!
    #
    - sudo apt-get install -y autoconf
                              automake
                              autotools-dev
                              checkbot
                              dia
                              docbook
                              docbook-xml
                              docbook-xsl
                              docbook-xsl-ns
                              docbook-xsl-saxon
                              docbook5-xml
                              fop
                              ghostscript
                              imagemagick
                              inkscape
                              jing
                              libimage-exiftool-perl
                              libsaxon-java
                              libtool
                              libxml-commons-external-java
                              libxml2
                              libxml2-utils
                              libxmlgraphics-commons-java
                              libxslt1.1
                              optipng
                              poppler-utils
                              python-libxml2
                              python-lxml
                              python3
                              remake
                              sgml-base
                              sgml-data
                              shtool
                              shunit2
                              transfig
                              w3m
                              xfig
                              xmlstarlet
                              xsltproc
                              zip
    #- sudo apt-cache show docbook-xml
    #- sudo apt-cache show docbook-xsl
    - git clone https://github.com/openSUSE/suse-xsl.git suse

install:
    - ./.travis-debug
    - ./configure --sysconfdir=/etc
    - make
    - sudo make install

script:
    # - make test
    - echo "Done"

# blacklist
branches:
    except:
        - gh-pages
